Import('env')
Import('prefix')

core_sources = Glob('*.cpp')
client_sources = Glob('client/*.cpp') + core_sources + Glob('client/standalone/*.cpp')
server_sources = Glob('server/*.cpp') + core_sources + Glob('server/standalone/*.cpp')
test_sources = Glob('test/*.cpp') + core_sources

env.Program(''.join(['#bin/', prefix, 'client']), client_sources)
env.Program(''.join(['#bin/', prefix, 'server']), server_sources)
env.Program(''.join(['#bin/', prefix, 'test']), test_sources)

